server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://cmcsv.com:3306/jeyeon?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: andy2350
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.example.board.domain

  configuration:
    map-underscore-to-camel-case: true
